name: uas_appmob_multiplatfrom
description: A new Flutter project.

# Baris berikut mencegah paket agar tidak dipublikasikan secara tidak sengaja ke
# pub.dev menggunakan `pub publish`. Ini lebih disukai untuk paket pribadi.
publish_to : ' none '  # Hapus baris ini jika Anda ingin mempublikasikan ke pub.dev

# Berikut ini mendefinisikan versi dan nomor build untuk aplikasi Anda.
# Nomor versi adalah tiga angka yang dipisahkan oleh titik, seperti 1.2.43
# diikuti dengan nomor build opsional yang dipisahkan dengan tanda +.
# Baik versi dan nomor pembuatnya dapat diganti dalam flutter
# build dengan menentukan --build-name dan --build-number, masing-masing.
# Di Android, build-name digunakan sebagai versionName sedangkan build-number digunakan sebagai versionCode.
# Baca selengkapnya tentang pembuatan versi Android di https://developer.android.com/studio/publish/versioning
# Di iOS, build-name digunakan sebagai CFBundleShortVersionString sedangkan build-number digunakan sebagai CFBundleVersion.
# Baca lebih lanjut tentang versi iOS di
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
versi : 1.0.0+1

lingkungan :
  sdk : " >=2.7.0 <3.0.0 "

dependensi :
  berdebar :
    sdk : berdebar-debar
  http : ^0.12.2

  # Berikut ini menambahkan font Cupertino Icons ke aplikasi Anda.
  # Gunakan dengan kelas CupertinoIcons untuk ikon gaya iOS.
  cupertino_icons : ^1.0.2

dev_dependencies :
  flutter_test :
    sdk : berdebar-debar

# Untuk informasi tentang bagian Dart generik dari file ini, lihat:
# halaman berikut: https://dart.dev/tools/pub/pubspec

# Bagian berikut khusus untuk Flutter.
berdebar :

  # Baris berikut memastikan bahwa font Material Icons adalah
  # disertakan dengan aplikasi Anda, sehingga Anda dapat menggunakan ikon di
  # kelas Ikon materi.
  kegunaan-bahan-desain : benar

  # Untuk menambahkan aset ke aplikasi Anda, tambahkan bagian aset, seperti ini:
  # aset:
  #    - gambar/a_dot_burr.jpeg
  #    - gambar/a_dot_ham.jpeg

  # Aset gambar dapat merujuk ke satu atau lebih "varian" khusus resolusi, lihat
  # https://flutter.dev/assets-and-images/# resolution-aware.

  # Untuk detail mengenai penambahan aset dari dependensi paket, lihat
  # https://flutter.dev/assets-and-images/#from-packages

  # Untuk menambahkan font khusus ke aplikasi Anda, tambahkan bagian font di sini,
  # di bagian "berkibar" ini. Setiap entri dalam daftar ini harus memiliki
  # kunci "keluarga" dengan nama keluarga font, dan kunci "font" dengan a
  # daftar memberikan aset dan deskriptor lain untuk font. Untuk
  # contoh:
  # font:
  #    - keluarga: Schyler
  #      font:
  #        - aset: fonts/Schyler-Regular.ttf
  #        - aset: fonts/Schyler-Italic.ttf
  #          gaya: miring
  #    - keluarga: Trajan Pro
  #      font:
  #        - aset: fonts/TrajanPro.ttf
  #        - aset: fonts/TrajanPro_Bold.ttf
  #          berat: 700
  #
  # Untuk detail mengenai font dari dependensi paket,
  # lihat https://flutter.dev/custom-fonts/#from-packages